export function useCodeIcon(): Record<string, string> {
  return {
    'package.json': 'vscode-icons:file-type-node',
    'tsconfig.json': 'vscode-icons:file-type-tsconfig',
    '.npmrc': 'vscode-icons:file-type-npm',
    '.editorconfig': 'vscode-icons:file-type-editorconfig',
    '.eslintrc': 'vscode-icons:file-type-eslint',
    '.gitignore': 'vscode-icons:file-type-git',
    '.env': 'vscode-icons:file-type-dotenv',
    '.env.example': 'vscode-icons:file-type-dotenv',
    '.vscode/settings.json': 'vscode-icons:file-type-vscode',
    'nuxt': 'vscode-icons:file-type-nuxt',
    'nuxt.config.ts': 'vscode-icons:file-type-nuxt',
    // Weme UI
    'style.ts': 'vscode-icons:file-type-unocss',
    'weme.config.json': 'weme:logo',
    'registry.json': 'weme:logo',
    'project.schema.json': 'weme:logo',
    'registry.schema.json': 'weme:logo',
    'vue': 'vscode-icons:file-type-vue',
    'ts': 'vscode-icons:file-type-typescript',
    'md': 'vscode-icons:file-type-markdown',
    'py': 'vscode-icons:file-type-python',
    'rs': 'vscode-icons:file-type-rust',
    'cargo': 'vscode-icons:file-type-cargo',
    'go': 'vscode-icons:file-type-go',
    'npm': 'vscode-icons:file-type-npm',
    'pnpm': 'vscode-icons:file-type-pnpm',
    'npx': 'vscode-icons:file-type-npm',
    'yarn': 'vscode-icons:file-type-yarn',
    'toml': 'vscode-icons:file-type-toml',
    'json': 'vscode-icons:file-type-json',
    'xml': 'vscode-icons:file-type-xml',
    'yml': 'vscode-icons:file-type-yaml',
    'sql': 'vscode-icons:file-type-sql',
    'prisma': 'vscode-icons:file-type-prisma',
    'mcp': 'vscode-icons:file-type-mcp',
    'terminal': 'lucide:terminal',
  }
}
