catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - undici-types@6.21.0
  - semver@6.3.1
  - ts-api-utils@2.3.0

packages:
  - docs
  - registry/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^7.0.1
  '@clack/core': ^0.5.0
  '@clack/prompts': ^0.11.0
  '@commitlint/cli': ^20.3.1
  '@commitlint/config-conventional': ^20.3.1
  '@iconify-json/lucide': 1.2.82
  '@iconify-json/mingcute': 1.2.6
  '@iconify-json/simple-icons': ^1.2.66
  '@inquirer/prompts': ^8.2.0
  '@nuxt/content': ^3.10.0
  '@nuxt/devtools': ^3.1.1
  '@nuxt/icon': ^2.2.0
  '@nuxt/image': ^2.0.0
  '@nuxt/kit': 4.0.3
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/schema': ^4.2.2
  '@radix-ui/colors': ^3.0.0
  '@tanstack/vue-table': ^8.21.3
  '@tanstack/vue-virtual': ^3.13.18
  '@types/columnify': ^1.5.4
  '@types/make-fetch-happen': ^10.0.4
  '@types/node': 24.0.15
  '@types/qrcode': ^1.5.6
  '@types/spark-md5': ^3.0.5
  '@typescript/native-preview': ^7.0.0-dev.20260115.1
  '@unocss/core': ^66.6.0
  '@unocss/nuxt': ^66.6.0
  '@unocss/rule-utils': ^66.6.0
  '@vee-validate/zod': ^4.15.1
  '@vitejs/plugin-vue': ^6.0.3
  '@vueuse/core': ^14.1.0
  '@zag-js/highlight-word': 1.31.1
  better-sqlite3: ^12.6.0
  bezier-easing: ^2.1.0
  bumpp: ^10.4.0
  chalk: ^5.6.2
  changelogen: ^0.6.2
  check-password-strength: ^3.0.0
  citty: ^0.1.6
  clsx: ^2.1.1
  colorjs.io: 0.5.2
  columnify: ^1.6.0
  commitizen: ^4.3.1
  compute-scroll-into-view: ^3.1.1
  cz-git: ^1.12.0
  czg: ^1.12.0
  debug: ^4.4.3
  defu: ^6.1.4
  diff: ^8.0.3
  embla-carousel: ^8.6.0
  embla-carousel-autoplay: ^8.6.0
  embla-carousel-fade: ^8.6.0
  embla-carousel-vue: ^8.6.0
  embla-carousel-wheel-gestures: ^8.1.0
  eslint: ^9.39.2
  eslint-plugin-pnpm: ^1.4.3
  esno: ^4.8.0
  handlebars: ^4.7.8
  jsbarcode: ^3.12.3
  jsonc-eslint-parser: ^2.4.2
  lint-staged: ^16.2.7
  log-symbols: ^7.0.1
  make-fetch-happen: ^15.0.3
  mkdirp: ^3.0.1
  motion-v: 1.7.4
  neverthrow: ^8.2.0
  nuxt: ^4.2.2
  nypm: ^0.6.2
  ora: ^9.0.0
  pathe: 2.0.3
  pkg-types: ^2.3.0
  premove: ^4.0.0
  qrcode: ^1.5.4
  reka-ui: ^2.7.0
  rfdc: ^1.4.1
  scule: ^1.3.0
  simple-git-hooks: ^2.13.1
  spark-md5: ^3.0.2
  tailwind-merge: ^3.4.0
  tailwind-variants: ^3.2.2
  taze: ^19.9.2
  tinyexec: ^1.0.2
  tinyglobby: ^0.2.15
  tsdown: ^0.19.0
  type-fest: ^5.4.1
  typescript: ^5.9.3
  ufo: ^1.6.3
  unocss: ^66.6.0
  vee-validate: ^4.15.1
  vite: ^7.3.1
  vitest: ^4.0.17
  vue: ^3.5.26
  vue-router: ^4.6.4
  vue-tsc: ^3.2.2
  yaml-eslint-parser: ^1.3.2
  zod: ^4.3.5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@weme-ui/schema'
  - better-sqlite3
  - esbuild
  - sharp
  - simple-git-hooks
  - vue-demi
