packages:
  - docs
  - registry/*
  - packages/*

catalogs:
  build:
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@types/node': 24.0.15
    '@typescript/native-preview': ^7.0.0-dev.20250827.1
    bumpp: ^10.2.3
    commitizen: ^4.3.1
    conventional-changelog: ^7.1.1
    cz-git: ^1.12.0
    czg: ^1.12.0
    simple-git-hooks: ^2.13.1
    taze: ^19.3.0
    tsdown: ^0.14.2
    typescript: ^5.9.2
    vite: ^7.1.3
  dev:
    '@nuxt/devtools': ^2.6.3
    '@nuxt/icon': ^2.0.0
    '@radix-ui/colors': ^3.0.0
    '@unocss/nuxt': ^66.4.2
    '@vueuse/core': ^13.8.0
    '@vueuse/nuxt': ^13.8.0
    bezier-easing: ^2.1.0
    clsx: ^2.1.1
    colorjs.io: ^0.5.2
    defu: ^6.1.4
    motion-v: ^1.7.0
    reka-ui: ^2.5.0
    tailwind-merge: ^3.3.1
    tailwind-variants: ^3.1.0
    ufo: ^1.6.1
    unocss: ^66.4.2
  docs:
    '@nuxt/content': ^3.6.3
    '@nuxtjs/i18n': ^10.0.6
    better-sqlite3: ^12.2.0
  icon:
    '@iconify-json/catppuccin': ^1.2.16
    '@iconify-json/lucide': ^1.2.65
    '@iconify-json/mingcute': ^1.2.5
    '@iconify-json/simple-icons': ^1.2.49
  lint:
    '@antfu/eslint-config': ^5.2.1
    eslint: ^9.34.0
    eslint-plugin-pnpm: ^1.1.1
    jsonc-eslint-parser: ^2.4.0
    lint-staged: ^16.1.5
    yaml-eslint-parser: ^1.3.0
  nuxt:
    '@nuxt/kit': ^4.0.3
    '@nuxt/module-builder': ^1.0.2
    '@nuxt/schema': ^4.0.3
    nuxt: ^4.0.3
  testing:
    '@nuxt/test-utils': ^3.19.2
    '@vue/test-utils': ^2.4.6
    happy-dom: ^18.0.1
    playwright-core: ^1.55.0
    vitest: ^3.2.4
  utils:
    citty: ^0.1.6
    consola: ^3.4.2
    debug: ^4.4.1
    diff: ^8.0.2
    execa: ^9.6.0
    fast-glob: ^3.3.3
    giget: ^2.0.0
    handlebars: ^4.7.8
    mkdirp: ^3.0.1
    nypm: ^0.6.1
    pathe: 2.0.3
    pkg-types: ^2.3.0
    scule: 1.3.0
    zod: ^4.1.4
  vue:
    '@vitejs/plugin-vue': ^6.0.1
    vue: ^3.5.20
    vue-tsc: ^3.0.6

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - simple-git-hooks
  - vue-demi
