packages:
  - docs
  - registry/*
  - packages/*

catalogs:
  build:
    '@antfu/eslint-config': ^6.2.0
    '@commitlint/cli': ^20.1.0
    '@commitlint/config-conventional': ^20.0.0
    '@types/node': 24.0.15
    '@typescript/native-preview': ^7.0.0-dev.20251106.1
    bumpp: ^10.3.1
    changelogen: ^0.6.2
    commitizen: ^4.3.1
    cz-git: ^1.12.0
    czg: ^1.12.0
    eslint: ^9.39.1
    eslint-plugin-pnpm: ^1.3.0
    esno: ^4.8.0
    jsonc-eslint-parser: ^2.4.1
    lint-staged: ^16.2.6
    premove: ^4.0.0
    simple-git-hooks: ^2.13.1
    taze: ^19.9.0
    tsdown: ^0.16.0
    typescript: ^5.9.3
    vite: ^7.2.2
    yaml-eslint-parser: ^1.3.0
  dev:
    '@nuxt/devtools': ^3.0.1
    '@nuxt/icon': ^2.1.0
    '@nuxt/image': ^2.0.0
    '@nuxt/kit': 4.0.3
    '@nuxt/module-builder': ^1.0.2
    '@nuxt/schema': ^4.2.1
    '@radix-ui/colors': ^3.0.0
    '@unocss/nuxt': ^66.5.4
    '@unocss/rule-utils': ^66.5.4
    '@vitejs/plugin-vue': ^6.0.1
    '@vueuse/nuxt': ^14.0.0
    '@weme-ui/schema': ^0.4.3
    bezier-easing: ^2.1.0
    colorjs.io: ^0.5.2
    defu: ^6.1.4
    nuxt: ^4.2.1
    ufo: ^1.6.1
    unocss: ^66.5.4
    vite-plugin-vue-devtools: ^8.0.3
    vue: ^3.5.23
    vue-router: ^4.6.3
    vue-tsc: ^3.1.3
  docs:
    '@nuxt/content': ^3.8.0
    '@nuxtjs/i18n': ^10.2.0
    better-sqlite3: ^12.4.1
  registry:
    '@iconify-json/catppuccin': ^1.2.17
    '@iconify-json/logos': ^1.2.10
    '@iconify-json/lucide': ^1.2.72
    '@iconify-json/mingcute': ^1.2.5
    '@iconify-json/simple-icons': ^1.2.57
    '@internationalized/date': ^3.10.0
    '@vueuse/core': ^14.0.0
    clsx: ^2.1.1
    motion-v: ^1.7.4
    reka-ui: ^2.6.0
    tailwind-merge: ^3.3.1
    tailwind-variants: ^3.1.1
  testing:
    '@nuxt/test-utils': ^3.20.1
    '@vue/test-utils': ^2.4.6
    happy-dom: ^20.0.10
    playwright-core: ^1.56.1
    vitest: ^4.0.7
  utils:
    '@clack/prompts': ^0.11.0
    '@types/columnify': ^1.5.4
    '@types/make-fetch-happen': ^10.0.4
    chalk: ^5.6.2
    citty: ^0.1.6
    columnify: ^1.6.0
    debug: ^4.4.3
    handlebars: ^4.7.8
    make-fetch-happen: ^15.0.2
    mkdirp: ^3.0.1
    nypm: ^0.6.2
    ora: ^9.0.0
    pathe: 2.0.3
    pkg-types: ^2.3.0
    scule: ^1.3.0
    tinyexec: ^1.0.2
    tinyglobby: ^0.2.15
    zod: ^4.1.12

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - sharp
  - simple-git-hooks
  - vue-demi
