packages:
  - registry/*
  - packages/*
  - docs

catalogs:
  build:
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@types/node': 24.0.15
    '@typescript/native-preview': 7.0.0-dev.20250718.1
    bumpp: 10.2.0
    commitizen: ^4.3.1
    conventional-changelog: ^7.1.1
    cz-git: ^1.12.0
    czg: ^1.12.0
    simple-git-hooks: ^2.13.0
    tsdown: 0.12.9
    typescript: 5.8.3
  cli:
    citty: 0.1.6
    consola: 3.4.2
    handlebars: ^4.7.8
    mkdirp: ^3.0.1
    pathe: 2.0.3
    rimraf: ^6.0.1
    scule: 1.3.0
  dev:
    '@mouji/modoc': ^1.0.0
    '@radix-ui/colors': ^3.0.0
    '@vitejs/plugin-vue': ^6.0.0
    bezier-easing: ^2.1.0
    colorjs.io: ^0.5.2
    nuxt: ^4.0.1
    unocss: ^66.3.3
    vite: 7.0.4
    vue: ^3.5.18
    vue-tsc: ^3.0.3
  lint:
    '@antfu/eslint-config': ^4.18.0
    eslint: 9.31.0
    eslint-plugin-pnpm: ^1.1.0
    jsonc-eslint-parser: ^2.4.0
    lint-staged: ^16.1.2
    yaml-eslint-parser: ^1.3.0
  registry:
    '@vueuse/core': ^13.5.0
    clsx: ^2.1.1
    reka-ui: ^2.4.0
    tailwind-merge: ^3.3.1
    tailwind-variants: ^1.0.0
  testing:
    '@nuxt/test-utils': ^3.19.2
    '@vue/test-utils': ^2.4.6
    happy-dom: ^18.0.1
    playwright-core: ^1.54.1
    vitest: 3.2.4

autoInstallPeers: true
shamefullyHoist: true
engineStrict: true
hoist: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks
