packages:
  - registry/*
  - packages/*
  - docs
  - scripts

catalogs:
  build:
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@types/node': 24.0.15
    '@typescript/native-preview': 7.0.0-dev.20250718.1
    bumpp: 10.2.0
    commitizen: ^4.3.1
    conventional-changelog: ^7.1.1
    cz-git: ^1.12.0
    czg: ^1.12.0
    simple-git-hooks: ^2.13.1
    taze: ^19.1.0
    tsdown: 0.12.9
    typescript: 5.8.3
    vite: 7.0.4
  cli:
    '@clack/prompts': ^0.11.0
    chalk: ^5.5.0
    citty: 0.1.6
    consola: 3.4.2
    diff: ^8.0.2
    execa: ^9.6.0
    handlebars: ^4.7.8
    mkdirp: ^3.0.1
    pathe: 2.0.3
    rimraf: ^6.0.1
    scule: 1.3.0
  dev:
    '@radix-ui/colors': ^3.0.0
    '@vitejs/plugin-vue': ^6.0.1
    '@vueuse/core': ^13.6.0
    bezier-easing: ^2.1.0
    clsx: ^2.1.1
    colorjs.io: ^0.5.2
    defu: ^6.1.4
    fast-glob: ^3.3.3
    reka-ui: ^2.4.1
    tailwind-merge: ^3.3.1
    tailwind-variants: ^2.1.0
    ufo: ^1.6.1
    unocss: ^66.4.1
    zod: ^4.0.15
    zod-to-json-schema: ^3.24.6
  icon:
    '@iconify-json/lucide': ^1.2.61
  lint:
    '@antfu/eslint-config': ^5.2.0
    eslint: 9.31.0
    eslint-plugin-pnpm: ^1.1.0
    jsonc-eslint-parser: ^2.4.0
    lint-staged: ^16.1.4
    yaml-eslint-parser: ^1.3.0
  nuxt:
    '@nuxt/content': ^3.6.3
    '@nuxt/devtools': ^2.6.2
    '@nuxt/icon': ^1.15.0
    '@nuxt/kit': ^4.0.3
    '@nuxt/module-builder': ^1.0.2
    '@nuxt/schema': ^4.0.3
    '@nuxt/test-utils': ^3.19.2
    '@nuxtjs/i18n': 10.0.1
    '@unocss/nuxt': ^66.4.1
    '@vueuse/nuxt': ^13.6.0
    better-sqlite3: ^12.2.0
    nuxt: ^4.0.3
  testing:
    happy-dom: ^18.0.1
    playwright-core: ^1.54.2
    vitest: 3.2.4
  vue:
    '@vue/test-utils': ^2.4.6
    vue: ^3.5.18
    vue-tsc: ^3.0.5

hoist: true
engineStrict: true
shamefullyHoist: true
autoInstallPeers: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - simple-git-hooks
  - vue-demi
