import { writeFile } from 'node:fs'
import { getColorNames, transformColor } from '@weme-ui/colors'
import { BG_BLACK, BG_WHITE } from '../src/defaults'

const wemeColors: Record<string, string> = {
  ocean: '#05f',
  gunmetal: '#1d2129',
  iron: '#86909c',
}

const neutralColors = ['iron']

const colorNames = [
  ...getColorNames(),
  ...Object.keys(wemeColors),
]

function invertBlackWhite(color: string) {
  if (color === 'black')
    return 'white'
  if (color === 'white')
    return 'black'
  return color
}

function prepareWemeColors() {
  const content: string[] = ['// Generated by @weme-ui/unocss-preset']

  content.push('export default {')
  colorNames.forEach((name) => {
    const color = wemeColors[name] ?? name

    content.push(`  ${name}: {`)
    // Light
    content.push('    light: {')
    transformColor({
      color,
      isNeutral: neutralColors.includes(name),
      appearance: 'light',
      background: BG_WHITE,
    }).forEach((c, i) => {
      content.push(`      ${i + 1}: '${c}',`)
    })
    content.push('    },')

    // Dark
    content.push('    dark: {')
    transformColor({
      color: invertBlackWhite(color),
      isNeutral: neutralColors.includes(name),
      appearance: 'dark',
      background: BG_BLACK,
    }).forEach((c, i) => {
      content.push(`      ${i + 1}: '${c}',`)
    })
    content.push('    },')
    content.push('  },')
  })

  content.push('}')

  writeFile('src/colors.ts', `${content.join('\n')}\n`, { encoding: 'utf8', flag: 'w' }, (err) => {
    if (err)
      throw err
  })

  console.log('[Prepare] Colors generated!\n')
}

function main() {
  prepareWemeColors()
}

main()
