import { writeFile } from 'node:fs'
import { transformColor } from '../src/colors/transformer'
import { ALL_COLOR_NAMES, EXTRA_COLORS } from '../src/defaults'

const neutralColors = ['iron']

const colorNames = [
  'black',
  'white',
  ...ALL_COLOR_NAMES,
  ...Object.keys(EXTRA_COLORS),
]

function invertBlackWhite(color: string) {
  if (color === 'black')
    return 'white'
  if (color === 'white')
    return 'black'
  return color
}

function prepareWemeColors() {
  const content: string[] = ['// Generated by @weme-ui/unocss-preset']

  content.push('export default {')
  colorNames.forEach((name) => {
    const color = EXTRA_COLORS[name] ?? name

    content.push(`  ${name}: {`)
    // Light
    content.push('    light: {')
    transformColor(
      color,
      'light',
      neutralColors.includes(name),
    ).forEach((c, i) => {
      content.push(`      ${i + 1}: '${c}',`)
    })
    content.push('    },')

    // Dark
    content.push('    dark: {')
    transformColor(
      invertBlackWhite(color),
      'dark',
      neutralColors.includes(name),
    ).forEach((c, i) => {
      content.push(`      ${i + 1}: '${c}',`)
    })
    content.push('    },')
    content.push('  },')
  })

  content.push('}')

  writeFile('src/colors.ts', `${content.join('\n')}\n`, { encoding: 'utf8', flag: 'w' }, (err) => {
    if (err)
      throw err
  })

  console.log('[Prepare] Colors generated!\n')
}

function main() {
  prepareWemeColors()
}

main()
