import type { NuxtTypeTemplate } from 'nuxt/schema'

export function createWemeConfigType(): NuxtTypeTemplate {
  return {
    filename: 'types/weme.config.d.ts',
    getContents() {
      return `// GENERATED BY @weme-ui/nuxt
interface WemeAppConfig {
  theme?: WemeThemeName
  radius?: string
  translucent?: boolean
  accentColor?: WemeAccentColorName
  neutralColor?: WemeNeutralColorName
  icons?: Partial<Record<WemeIconName, string>>
}

declare module '@nuxt/schema' {
  interface AppConfigInput {
    weme?: WemeAppConfig
  }

  interface AppConfig {
    weme: Omit<WemeAppConfig, 'theme' | 'icons'> & Required<Pick<WemeAppConfig, 'theme' | 'icons'>>
  }
}

export {}`
    },
  }
}
