import type { NuxtTemplate } from 'nuxt/schema'

export function createWemeStyles(): NuxtTemplate {
  const colors = ['accent', 'neutral', 'info', 'success', 'warning', 'error']
  const variants = ['solid', 'soft', 'surface', 'outline', 'ghost', 'link', 'inverse']
  const states = ['normal', 'hover', 'active']

  return {
    filename: 'weme/styles.ts',
    getContents() {
      return `// GENERATED BY @weme-ui/nuxt
export type ColorName = ${colors.map(c => `'${c}'`).join(' | ')}
export type StateName = ${states.map(s => `'${s}'`).join(' | ')}
export type VariantName = ${variants.map(v => `'${v}'`).join(' | ')}
export type VariantNameMap = Record<string, VariantName>

type ColorVariantClasses = Record<
  ColorName,
  {
    variant: VariantName
    state: StateName
    class: string
  }[]
>

export const colorStyles: ColorVariantClasses = {
${colors.map(
  color => (`  ${color}: [
${variants.map((variant) => {
      function skip(value: string, key: string): string {
        return key === value ? '' : `-${key}`
      }

      return states.map((state) => {
        return `    { variant: '${variant}', state: '${state}', class: 'ui-${color}${skip('solid', variant)}${skip('normal', state)}' },`
      }).join('\n')
    }).join('\n')}
  ]`),
).join(',\n')}
}
`
    },
    write: true,
  }
}
