import type { NuxtTemplate } from 'nuxt/schema'
import { THEME_COLORS, VARIANT_MAP } from '@weme-ui/unocss-preset'

export function createWemeStyles(): NuxtTemplate {
  return {
    filename: 'weme/styles.ts',
    getContents() {
      return `// GENERATED BY @weme-ui/nuxt
export type TypeName = ${Object.keys(VARIANT_MAP).map(c => `'${c}'`).join(' | ')}
export type ColorName = ${THEME_COLORS.map(c => `'${c}'`).join(' | ')}

type ColorVariantClasses = Record<
  ColorName,
  {
    type: TypeName
    variant: string
    class: string
  }[]
>

export const colorStyles: ColorVariantClasses = {
${THEME_COLORS.map(
  color => (`  ${color}: [
${Object.entries(VARIANT_MAP).map(([type, variants]) => {
      function skip(value: string, key: string): string {
        return key === value ? '' : `-${key}`
      }

      return variants.map((variant) => {
        return `    { variant: '${variant}', type: '${type}', class: '${type}-${color}${skip('solid', variant)}' },`
      }).join('\n')
    }).join('\n')}
  ]`),
).join(',\n')}
}
`
    },
    write: true,
  }
}
