import type { WemeThemeDefinition } from '@weme-ui/unocss-preset'
import type { NuxtTemplate } from 'nuxt/schema'
import type { WemeNuxtOptions } from '../module'
import { resolveThemes } from '@weme-ui/unocss-preset'

export function createWemeThemes(
  themes: WemeThemeDefinition[],
  background: WemeNuxtOptions['background'],
  prefix: WemeNuxtOptions['prefix'],
): NuxtTemplate {
  const resolvedThemes = resolveThemes(
    themes,
    background!,
    prefix!,
    false,
  ).map((theme) => {
    return {
      ...theme,

      colors: {
        accent: theme.colors.accent[8],
        neutral: theme.colors.neutral[8],
        info: theme.colors.info[8],
        success: theme.colors.success[8],
        warning: theme.colors.warning[8],
        error: theme.colors.error[8],
      },
    }
  })

  return {
    filename: 'weme/themes.ts',
    getContents() {
      return `// GENERATED BY @weme-ui/nuxt
export default ${JSON.stringify(resolvedThemes, null, 2)}
`
    },
    write: true,
  }
}
