import type { NuxtTypeTemplate } from 'nuxt/schema'
import type { WemeThemeDefinition } from '../runtime/types'
import { WemeIcons } from '../runtime/icons'

export function createWemeType(
  themes: WemeThemeDefinition[],
  accentColors: string[],
  neutralColors: string[],
): NuxtTypeTemplate {
  const themeNames = themes.map(t => `'${t.id}'`).join(' | ')
  const accentColorNames = accentColors.map(c => `'${c}'`).join(' | ')
  const neutralColorNames = neutralColors.map(c => `'${c}'`).join(' | ')
  const wemeIconNames = Object.keys(WemeIcons).map(c => `'${c}'`).join(' | ')

  return {
    filename: 'types/weme.d.ts',
    getContents() {
      return `// GENERATED BY @weme-ui/nuxt
declare type WemeThemeName = ${themes.length ? themeNames : 'string'}
declare type WemeThemeColorName = 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error'
declare type WemeAccentColorName = ${accentColors.length ? accentColorNames : 'string'}
declare type WemeNeutralColorName = ${neutralColors.length ? neutralColorNames : 'string'}
declare type WemeIconName = ${wemeIconNames}
`
    },
  }
}
